apiVersion: v1
kind: Service
metadata:
  name: kepler
  namespace: kepler
  labels:
    app: kepler
spec:
  ports:
    - name: metrics
      port: 9102
      targetPort: 9102
      protocol: TCP
  selector:
    app: kepler
  type: ClusterIP
