apiVersion: v1
kind: Service
metadata:
  name: sample-app
  namespace: sample-workload
  labels:
    app: sample-app
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: sample-app
  type: ClusterIP
